apiVersion: v1
kind: Service
metadata:
  name: developer-tools-site-service
spec:
  type: NodePort
  selector:
    app: developer-tools-site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080