apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-tools-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: developer-tools-site
  template:
    metadata:
      labels:
        app: developer-tools-site
    spec:
      containers:
      - name: web
        image: sumanthmaddali/developertools:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-config-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: html-config-volume
          mountPath: /usr/share/nginx/html/style.css
          subPath: style.css
      volumes:
      - name: html-config-volume
        configMap:
          name: html-config
